const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const targetUrl = process.env.TEST_URL || pathToFileURL(path.join(__dirname, 'index.html')).href;

(async () => {
  const browser = await chromium.launch({ ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}), headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
    const page = await context.newPage();
    const errors = [], remote = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    page.on('request', r => { if (/^https?:/.test(r.url()) && (!process.env.TEST_URL || new URL(r.url()).origin !== new URL(targetUrl).origin || r.method() !== 'GET')) remote.push(r.url()); });
    await page.goto(targetUrl);
    assert.equal(await page.evaluate(() => typeof firebase.initializeApp), 'function');
    if (process.env.FIREBASE_PROJECT_ID) {
      assert.equal(await page.evaluate(() => firebase.app().options.projectId), process.env.FIREBASE_PROJECT_ID);
    }
    await page.locator('.column').first().waitFor();
    assert.equal(await page.locator('.column').count(), 4);
    await page.screenshot({ path: path.join(__dirname, 'preview-desktop.png'), fullPage: true });
    await page.locator('#new-task').click();
    await page.locator('#task-title').fill('Preparar propuesta');
    await page.locator('#task-content').fill('Revisar las ideas y definir los siguientes pasos.');
    await page.locator('#task-image').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') });
    await page.locator('#image-preview').waitFor({ state: 'visible' });
    await page.locator('#submit-task').click();
    assert.equal(await page.locator('.card').count(), 1);
    assert.equal(await page.locator('.card-cover').evaluate(n => n.complete && n.naturalWidth > 0), true);
    await page.waitForFunction(() => document.getElementById('storage-title').textContent === 'Guardado en este navegador');
    await page.reload();
    await page.locator('.card-cover').waitFor();
    assert.equal(await page.locator('.card-cover').evaluate(n => n.complete && n.naturalWidth > 0), true);
    assert.match(await page.locator('.card').textContent(), /Revisar las ideas/);
    await page.locator('.card').click();
    await page.locator('#task-title').fill('Propuesta revisada');
    await page.locator('#task-column').selectOption({ label: 'Hoy' });
    await page.locator('#submit-task').click();
    assert.equal(await page.locator('.column').nth(1).locator('.card').count(), 1);
    await page.locator('.card').dragTo(page.locator('.column').nth(2).locator('.card-list'));
    assert.equal(await page.locator('.column').nth(2).locator('.card').count(), 1);
    await page.locator('.column').nth(2).locator('.add-task').click();
    await page.locator('#task-title').fill('Segunda tarea');
    await page.locator('#submit-task').click();
    await page.locator('.column').nth(2).locator('.card').nth(1).dragTo(page.locator('.column').nth(2).locator('.card').nth(0), { targetPosition: { x: 30, y: 5 } });
    assert.match(await page.locator('.column').nth(2).locator('.card').first().textContent(), /Segunda tarea/);
    await page.locator('.add-column').click();
    await page.locator('#column-name').fill('En revisión');
    await page.locator('#column-form button[type=submit]').click();
    assert.equal(await page.locator('.column').count(), 5);
    await page.locator('.column').last().locator('summary').click();
    await page.getByRole('button', { name: 'Renombrar columna', exact: true }).last().click();
    await page.locator('#column-name').fill('Revisión final');
    await page.locator('#column-color').selectOption({ label: 'Melocotón' });
    await page.locator('#column-form button[type=submit]').click();
    assert.equal(await page.locator('.column h2').last().textContent(), 'Revisión final');
    await page.waitForFunction(() => document.getElementById('storage-title').textContent === 'Guardado en este navegador');
    await page.reload();
    await page.locator('.column').last().waitFor();
    assert.equal(await page.locator('.column').count(), 5);
    assert.equal(await page.locator('.column').last().evaluate(n => n.style.getPropertyValue('--column-color')), '#d9b89d');
    assert.match(await page.locator('.column').nth(2).locator('.card').first().textContent(), /Segunda tarea/);
    await page.locator('.column').last().locator('summary').click();
    await page.getByRole('button', { name: 'Eliminar columna', exact: true }).last().click();
    await page.locator('#confirm-delete').click();
    assert.equal(await page.locator('.column').count(), 4);
    await page.locator('.card').first().click();
    await page.locator('#delete-task').click();
    await page.locator('#confirm-delete').click();
    assert.equal(await page.locator('.card').count(), 1);
    await page.locator('.card').click();
    await page.locator('#remove-image').click();
    await page.locator('#submit-task').click();
    assert.equal(await page.locator('.card-cover').count(), 0);
    await page.locator('#new-task').click();
    await page.locator('#task-title').fill('   ');
    await page.locator('#submit-task').click();
    assert.equal(await page.locator('#task-title').evaluate(n => n.checkValidity()), false);
    await page.keyboard.press('Escape');
    await page.locator('#task-dialog').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#new-task').evaluate(n => n === document.activeElement), true);
    await page.reload();
    await page.locator('.card').waitFor();
    assert.equal(await page.locator('.card').count(), 1);
    assert.equal(await page.locator('.card-cover').count(), 0);
    assert.equal(await page.locator('.column').count(), 4);
    assert.deepEqual(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length })), { local: 0, session: 0 });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(__dirname, 'preview-mobile.png'), fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator('#new-task').click();
    await page.screenshot({ path: path.join(__dirname, 'preview-modal.png'), fullPage: true });
    await page.keyboard.press('Escape');
    const reopened = await context.newPage();
    await reopened.goto(targetUrl);
    await reopened.locator('.card').waitFor();
    assert.match(await reopened.locator('.card').textContent(), /Propuesta revisada/);
    await reopened.evaluate(() => { IDBObjectStore.prototype.put = () => { throw new DOMException('Full', 'QuotaExceededError'); }; });
    await reopened.locator('#new-task').click();
    await reopened.locator('#task-title').fill('Cambio que no cabe');
    await reopened.locator('#submit-task').click();
    assert.equal(await reopened.locator('#storage-title').textContent(), 'Cambios sin guardar');
    await reopened.reload();
    await reopened.locator('.card').waitFor();
    assert.equal(await reopened.locator('.card').count(), 1);
    await reopened.close();
    assert.deepEqual(errors, []);
    assert.deepEqual(remote, []);
    const touchContext = await browser.newContext({ viewport: { width: 800, height: 1000 }, hasTouch: true, isMobile: true });
    const touchPage = await touchContext.newPage();
    await touchPage.goto(targetUrl);
    await touchPage.locator('.column').first().waitFor();
    await touchPage.locator('#new-task').click();
    await touchPage.locator('#task-title').fill('Tarea táctil');
    await touchPage.locator('#submit-task').click();
    const source = await touchPage.locator('.card').boundingBox();
    const destination = await touchPage.locator('.column').nth(1).locator('.card-list').boundingBox();
    const cdp = await touchContext.newCDPSession(touchPage);
    const start = { x: source.x + 60, y: source.y + 20 };
    const end = { x: destination.x + 70, y: destination.y + 35 };
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [start] });
    await touchPage.waitForFunction(() => document.body.classList.contains('pointer-dragging'));
    for (let i = 1; i <= 8; i++) await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: start.x + (end.x - start.x) * i / 8, y: start.y + (end.y - start.y) * i / 8 }] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    assert.equal(await touchPage.locator('.column').nth(1).locator('.card').count(), 1);
    await touchContext.close();
    console.log('PASS: tareas e imágenes persistentes en IndexedDB, colores, orden, borrado persistente, drag & drop de ratón y táctil, responsive, validación, foco y cero peticiones externas.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });

